language: csharp
solution: ThermoRawFileParser.sln

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GH_TOKEN
  file_glob: true
  file:
    - "bin/Debug/*"
  on:
    tags: true
